### ISSUE TITLE
В версии 1.40 нету скама :(

### ISSUE THREAD

**Issue by nikonufrienko** [vitekkor/computer_graphics_scam#2]
![image](https://user-images.githubusercontent.com/25980970/190899508-ea4c894e-dcd9-45b1-8089-66110a227d43.png)

**Comment by vitekkor** [comment]
В версии 1.4.0 его и не будет. Это переходная версия для тестирования CI/CD. Ждите 2.0 - фикс уже есть, в процессе тестирования. Выйдет скоро (возможно даже сегодня)

**Comment by nikonufrienko** [comment]
О, спс
