### ISSUE TITLE
Не работает :( 

### ISSUE THREAD

**Issue by nikonufrienko** [vitekkor/computer_graphics_scam#4]
Работает только для первого задания второй недели.
![image](https://user-images.githubusercontent.com/25980970/194778889-e2042c95-1bcc-45b8-9f19-8f8f228656ce.png)
Далее во всех заданиях такая картина:
![image](https://user-images.githubusercontent.com/25980970/194778907-4b38caef-7312-4b39-b2e7-1ed672d0912a.png)

P.S. Сотку на пивас перевёл.
#

**Comment by nikonufrienko** [comment]
Проверил как на линухе так и на винде.

**Comment by vitekkor** [comment]
@nikonufrienko Попробуй на странице прожать ctrl+r или f5 для перезагрузки страницы, скрипт может не прогрузился

**Comment by vitekkor** [comment]
@nikonufrienko Отпиши тут решилась ли проблема

**Comment by nikonufrienko** [comment]
Да вроде решилась, спасибо
